# Generated by Django 3.1 on 2021-04-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210405_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in stock', 'В наличии'), ('out of stock', 'Нет в наличии'), ('await', 'Ожидается')], max_length=20),
        ),
    ]
